version: '3'

services:

  issuer:
    platform: linux/x86_64
    restart: always
    container_name: issuer
    image: issuer
    build:
      context: issuer
    ports:
      - "3000:3000"
    networks:
      - di_network

  verifier:
    platform: linux/x86_64
    restart: always
    container_name: verifier
    image: verifier
    build:
      context: verifier
    ports:
      - "3000:3000"
    networks:
      - di_network

networks:
  di_network:
