version: '3'

services:

  issuer:
    platform: linux/x86_64
    restart: always
    container_name: issuer
    image: issuer
    build:
      context: .
    ports:
      - "3000:3000"
    networks:
      - issuer_network

networks:
  issuer_network:
